name: CI

on: [push]

jobs:
  package:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Package addon
        run: |
          make
      - name: Upload packaged addon
        uses: actions/upload-artifact@v2
        with:
          name: io_mesh_md2
          path: ./dist/*.zip